name: deploy documentation ko
on:
  push:
    branches:
      - 'docs-ko'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    deploy:
      # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
      permissions:
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate 
      environment:
        name: github-pages
        url: https://anpigon.github.io/khoj
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        # 👇 Build steps
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 18.x
            cache: yarn
            cache-dependency-path: documentation-ko/yarn.lock
        - name: Install dependencies
          run: |
            cd documentation-ko
            yarn install --frozen-lockfile --non-interactive
        - name: Build
          run: |
            cd documentation-ko
            yarn build
        # 👆 Build steps
        - name: Setup Pages
          uses: actions/configure-pages@v5
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
            # 👇 Specify build output path
            path: documentation-ko/build
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
